import Phone1 from "../../assets/images/phones/phone1.svg";
import Phone2 from "../../assets/images/phones/phone2.svg";
import Phone3 from "../../assets/images/phones/phone3.svg";
import Phone4 from "../../assets/images/phones/phone4.svg";
import Phone5 from "../../assets/images/phones/phone5.svg";



export const SAMPLE_PHONES_PRODUCTS_LIST = [
    {
    id: "1121",
    imageFile: Phone1,
    brand : "iphone",
    name: " APPLE iPhone 13 (Midnight, 128 GB)",
    currrentPrice : "₹58,900" ,
    originalPrice : "₹69,900",
    discount: "15% Off",
    offer:"12% cashback" ,
    emi: "EMI starts @ ₹1365",
    availablecolors : ["red","blue","black","white"],
    keyfeatures : ["5000 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],


},
{
    id: "1122",
    imageFile: Phone2 ,
    brand : "Nothing",
    name: "Nothing Phone (2) (Dark Grey, 512 GB)",
    currrentPrice : "₹45,999" ,
    originalPrice : "₹59,999",
    discount: "23% off",
    offer:"10% cashback" ,
    emi: "EMI starts @ ₹7,667",
    availablecolors : ["green","silver ","blue","white"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],
},
{
    id: "1123",
    imageFile: Phone3,
    brand : "OnePlus",
    name: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)",
    currrentPrice : "₹16,895" ,
    originalPrice : "₹19,999",
    discount: "15% Off",
    offer:"15% cashback" ,
    emi: "EMI starts @ ₹2,816",
    availablecolors : ["black","red ", "white"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1124",
    imageFile: Phone4,
    brand : "POCO",
    name: "POCO C55 (Forest Green, 64 GB)  (4 GB RAM)",
    currrentPrice : "₹6,499" ,
    originalPrice : "₹11,999",
    discount: "45% off",
    offer:"5% cashback" ,
    emi: "EMI starts @  ₹2,167",
    availablecolors : ["white","red ","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1125",
    imageFile: Phone5,
    brand : "POCO",
    name: "POCO M6 Pro 5G (Power Black, 128 GB)",
    currrentPrice : "₹11,999" ,
    originalPrice : "₹16,999",
    discount: "29% off",
    offer:"7% cashback" ,
    emi: "EMI starts @  ₹422",
    availablecolors : ["gold","white ","blue","red"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1131",
    imageFile: Phone1,
    brand : "iPhone",
    name: " APPLE iPhone 13 (Midnight, 128 GB)",
    currrentPrice : "₹58,900" ,
    originalPrice : "₹69,900",
    discount: "15% Off",
    offer:"12% cashback" ,
    emi: "EMI starts @ ₹1365",
    availablecolors : ["white","black ","blue","red"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],



},
{
    id: "1132",
    imageFile: Phone2 ,
    brand : "Nothing",
    name: "Nothing Phone (2) (Dark Grey, 512 GB)",
    currrentPrice : "₹45,999" ,
    originalPrice : "₹59,999",
    discount: "23% off",
    offer:"10% cashback" ,
    emi: "EMI starts @ ₹7,667",
    availablecolors : ["red","black ","green","red"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1133",
    imageFile: Phone3,
    brand : "OnePlus",
    name: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)",
    currrentPrice : "₹16,895" ,
    originalPrice : "₹19,999",
    discount: "15% Off",
    offer:"15% cashback" ,
    emi: "EMI starts @ ₹2,816",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1134",
    imageFile: Phone4,
    brand : "POCO",
    name: "POCO C55 (Forest Green, 64 GB)  (4 GB RAM)",
    currrentPrice : "₹6,499" ,
    originalPrice : "₹11,999",
    discount: "45% off",
    offer:"5% cashback" ,
    emi: "EMI starts @  ₹2,167",
    availablecolors : ["yellow","green ","black","red"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1135",
    imageFile: Phone5,
    brand : "POCO",
    name: "POCO M6 Pro 5G (Power Black, 128 GB)",
    currrentPrice : "₹11,999" ,
    originalPrice : "₹16,999",
    discount: "29% off",
    offer:"7% cashback" ,
    emi: "EMI starts @  ₹422",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1141",
    brand : "iPhone",
    imageFile: Phone1,
    name: " APPLE iPhone 13 (Midnight, 128 GB)",
    currrentPrice : "₹58,900" ,
    originalPrice : "₹69,900",
    discount: "15% Off",
    offer:"12% cashback" ,
    emi: "EMI starts @ ₹1365",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],


},
{
    id: "1142",
    imageFile: Phone2 ,
    brand : "Nothing",
    name: "Nothing Phone (2) (Dark Grey, 512 GB)",
    currrentPrice : "₹45,999" ,
    originalPrice : "₹59,999",
    discount: "23% off",
    offer:"10% cashback" ,
    emi: "EMI starts @ ₹7,667",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1143",
    imageFile: Phone3,
    brand : "OnePlus",
    name: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)",
    currrentPrice : "₹16,895" ,
    originalPrice : "₹19,999",
    discount: "15% Off",
    offer:"15% cashback" ,
    emi: "EMI starts @ ₹2,816",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1144",
    imageFile: Phone4,
    brand : "POCO",
    name: "POCO C55 (Forest Green, 64 GB)  (4 GB RAM)",
    currrentPrice : "₹6,499" ,
    originalPrice : "₹11,999",
    discount: "45% off",
    offer:"5% cashback" ,
    emi: "EMI starts @  ₹2,167",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1145",
    imageFile: Phone5,
    brand : "POCO",
    name: "POCO M6 Pro 5G (Power Black, 128 GB)",
    currrentPrice : "₹11,999" ,
    originalPrice : "₹16,999",
    discount: "29% off",
    offer:"7% cashback" ,
    emi: "EMI starts @  ₹422",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1151",
    imageFile: Phone1,
    brand : "iPhone",
    name: " APPLE iPhone 13 (Midnight, 128 GB)",
    currrentPrice : "₹58,900" ,
    originalPrice : "₹69,900",
    discount: "15% Off",
    offer:"12% cashback" ,
    emi: "EMI starts @ ₹1365",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1152",
    imageFile: Phone2 ,
    brand : "Nothing",
    name: "Nothing Phone (2) (Dark Grey, 512 GB)",
    currrentPrice : "₹45,999" ,
    originalPrice : "₹59,999",
    discount: "23% off",
    offer:"10% cashback" ,
    emi: "EMI starts @ ₹7,667",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1153",
    imageFile: Phone3,
    brand : "OnePlus",
    name: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)",
    currrentPrice : "₹16,895" ,
    originalPrice : "₹19,999",
    discount: "15% Off",
    offer:"15% cashback" ,
    emi: "EMI starts @ ₹2,816",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1154",
    imageFile: Phone4,
    brand : "POCO",
    name: "POCO C55 (Forest Green, 64 GB)  (4 GB RAM)",
    currrentPrice : "₹6,499" ,
    originalPrice : "₹11,999",
    discount: "45% off",
    offer:"5% cashback" ,
    emi: "EMI starts @  ₹2,167",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},
{
    id: "1155",
    imageFile: Phone5,
    brand : "POCO",
    name: "POCO M6 Pro 5G (Power Black, 128 GB)",
    currrentPrice : "₹11,999" ,
    originalPrice : "₹16,999",
    discount: "29% off",
    offer:"7% cashback" ,
    emi: "EMI starts @  ₹422",
    availablecolors : ["red","green ","blue","yellow","black"],
    keyfeatures : ["4700 mAh Lithium ion Battery",
                    "Qualcomm Snapdragon 8+ Gen 1 Processor",
                    "LTPO AMOLED (1 Hz - 120 Hz)",                                    
],

},


];